### ISSUE TITLE
theme is laggy

### ISSUE THREAD

**Issue by crusherXF** [warrayquipsome/Chillax#1]
well the theme is pretty laggy and I tried waiting for a few minutes just like it said in the discord support server, but it is still pretty laggy even though my computer can handle most themes well without lagging. so is there a way to fix this? it is a pretty good theme. maybe remove some of the unnecessary animations or have a version that is made for low end pcs idk

**Comment by Sebas-Re** [comment]
![image](https://user-images.githubusercontent.com/32151264/195215704-2e0dc6ae-70dd-42e3-ade4-9e8a15695ccf.png)

The reason why it's laggy it's because animations (even the smaller ones, like the ones from this corner) consumes up to 50% of GPU, which is insane honestly. 
Also, the window that pops up when you click your profile icon flickers a bit when clicking it

**Comment by Sebas-Re** [comment]
![image](https://user-images.githubusercontent.com/32151264/195215914-b7829c72-3a64-4a38-b607-7d03da066e51.png)

For example, hovering over online friends can increase gpu usage up to 44,2%

**Comment by Sebas-Re** [comment]
Also, if you thought 1.0.2 was laggy... Don't even try 1.0.3 lol
Now even my CPU is going crazy, to the point you can't even use the theme properly xDDDDDDDDD

**Comment by Sebas-Re** [comment]
lol
